### ISSUE TITLE
It does not finish analyzing the frames

### ISSUE THREAD

**Issue by steniooliv** [dealfonso/simplelottieplayer#1]
First congratulations for the work, I think the removal of margins is essential for those who develop, especially for me on mobile. And having to pay Adobe just for that is very complicated.

![image](https://github.com/dealfonso/simplelottieplayer/assets/21336806/499f22f7-17f5-4cde-9aa3-5819a83f47d1)

I tried to upload two files and both are analyzing the frame and it doesn't complete, I'm using Chrome on macOS, do I have to do something?

**Comment by steniooliv** [comment]
I made several attempts, and I noticed that the process of generating the Lottie is happening, the problem is just the html modal that is not disappearing.

Editing the HTML I was able to remove it and have access to the download button.

using display: none in all modal tags
![image](https://github.com/dealfonso/simplelottieplayer/assets/21336806/75882714-89ea-45ff-a3d6-db3541019072)

**Comment by dealfonso** [comment]
Hi,

Thank you for your greetings :)

I have just tried the current version, both opening the file as is in the browser and using a local web server, and also the one published at [https://dealfonso.github.io/simplelottieplayer/lottietrimmer.html](https://dealfonso.github.io/simplelottieplayer/lottietrimmer.html), and anything seems to work as expected.

I have also tried multiple browsers (Chrome, Safari, Edge, and Brave) and found no issues. Could you please send me an example of Lottie file to check if it depends on the specific use case? 

I appreciate any help you can provide.
