### ISSUE TITLE
add horizontal and vertical resizing sliders, to further customize the trimmed result

### ISSUE THREAD

**Issue by ginobean** [dealfonso/simplelottieplayer#2]
Trimming looks pretty cool! But it would be nice to be able to further customize the trimmed result, by dragging sliders, 
to further customize the trimmed result. For example, I want to resize a checkbox animation, and the trimmed result 
is almost there. But the checkbox has explosions which put an absolute constraint on the trimmed result. 

I don't care if some of the explosions' outer positions get trimmed out. I want to zoom in on the animation even more than 
the default trimming will allow.

Additionally, from the initial trim, you should be able determine the "center" of the animation. A reasonable assumption would be to keep this computed "center" constant, when allowing the user to resize the width/height of the trimmed animation.

**Comment by dealfonso** [comment]
Hi,

Thank you for your comments. Currently, the library allows the user to customize the crop box, but I have not included any graphical user interface to make it yet. I wanted to make the application more straightforward, but you are right that it would be nice if the crop box could be customized.

I am working on an interface to select the crop box visually. The hard part is the user interface. :)

I'll let you know.

** Sorry, but I did not understand the purpose of the "center" that you mentioned in your comment.

**Comment by ginobean** [comment]
Awesome! Thanks! :).

**Comment by dealfonso** [comment]
Hi,
I have just added the option to select a custom trimming box. It is both included in the `lottietrimmer.html` example and in the public app at https://dealfonso.github.io/simplelottieplayer/lottietrimmer.html

**Comment by ginobean** [comment]
Nice job! Exactly what I needed! Thanks! :).
