### ISSUE TITLE
Trimmer not loading files?

### ISSUE THREAD

**Issue by ilazakis** [dealfonso/simplelottieplayer#3]
Hey 👋 Thanks for putting this together; the trimmer in particular has been really useful!

Is the trimmer still expected to be functional? I tried to upload Lottie files today after a few months since I last used it using: 

- Recent versions of Safari and Chrome, on two different MacBooks
- Recent version of Safari on iPhone
- Both drag & drop, and using the file system uploader

In all cases, the animation seems to not be loading at all.

<img width="811" alt="image" src="https://github.com/user-attachments/assets/c298b10e-f74f-4386-8d46-b05c8023ba35">

The player works as expected — it's the trimmer that seems to not be uploading or handling the uploaded file correctly.

**Comment by ronaldpostma** [comment]
Hi Carlos! First of all like above, indeed many thanks for making and sharing this - it's totally unique and impossible to trim lottie's any other easy way.

It's classic not to say thanks when things work well, and only to comment when something is wrong. But indeed, hands up for the bug mentioned by @ilazakis

**Comment by dealfonso** [comment]
Hi,

now it seems to be working. Thank you for your support!

Regards

**Comment by ilazakis** [comment]
I can confirm it is working as expected.

I don’t see any commits, so it was presumably something to do with the server?

Much appreciated, thanks for the quick turnaround @dealfonso 🙏

**Comment by dealfonso** [comment]
hi,
yes... it was simply a bug in the user interface
